hmcts/rd-judicial-data-load

build.gradle, src/main/java/uk/gov/hmcts/reform/judicialapi/JudicialApplication.java, src/main/java/uk/gov/hmcts/reform/judicialapi/camel/AzureBlobConnector.java, src/main/java/uk/gov/hmcts/reform/judicialapi/camel/JrdCsvDataMapper.java, src/main/java/uk/gov/hmcts/reform/judicialapi/camel/JrdFileProcessorRoute.java, src/main/java/uk/gov/hmcts/reform/judicialapi/camel/JudicialOfficeAppointmentProcessorRoute.java, src/main/java/uk/gov/hmcts/reform/judicialapi/camel/JudicialOfficeAuthorisationrRoute.java, src/main/java/uk/gov/hmcts/reform/judicialapi/camel/JudicialUserFileProcessorRoute.java, src/main/java/uk/gov/hmcts/reform/judicialapi/configuration/StorageCredentials.java, src/main/java/uk/gov/hmcts/reform/judicialapi/service/impl/PushFileToBlobServiceImpl.java, src/main/resources/application.yaml, src/main/resources/db/migration/V1_1__init_tables.sql, src/main/resources/my-camel.xml
RDCC-672
changes for camel route related merging to master.
```
[ ] Yes
[ X] No
```
=> Rdcc 672 v2

Jenkinsfile_CNP, build.gradle, charts/rd-judicial-data-load/Chart.yaml, config/owasp/suppressions.xml, infrastructure/main.tf, infrastructure/variables.tf, src/main/java/uk/gov/hmcts/reform/juddata/configuration/StorageCredentials.java, src/main/java/uk/gov/hmcts/reform/juddata/orchestrator/impl/BlobStoreOrchestratorImpl.java, src/main/java/uk/gov/hmcts/reform/juddata/scheduler/JrdBlobScheduler.java, src/main/java/uk/gov/hmcts/reform/juddata/service/impl/FileDecryptionServiceImpl.java
RDCC-733
Pipline changes
```
[ ] Yes
[X] No
```
=> RDCC-733 Initial draft for sftp , decryption and blob store transfer

.gitignore, infrastructure/main.tf, src/main/resources/application.yaml
NA
refactor: removed s2s secrets
No
=> refactor: removed s2s secrets

src/main/java/uk/gov/hmcts/reform/juddata/service/impl/PushFileToBlobServiceImpl.java
Adding logger to restart aat pods
```
[ ] Yes
[X] No
```
=> Adding logger to restart aat pods

src/main/java/uk/gov/hmcts/reform/juddata/orchestrator/impl/BlobStoreOrchestratorImpl.java, src/main/java/uk/gov/hmcts/reform/juddata/service/impl/FileDecryptionServiceImpl.java, src/main/java/uk/gov/hmcts/reform/juddata/service/impl/PushFileToBlobServiceImpl.java
Enable decryption since it was supressed because key vaults having problem for public , private key
```
[ ] Yes
[X] No
```
=> Enable decryption

build.gradle, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/juddata/service/impl/PushFileToBlobServiceImpl.java
changed blob details
```
[ ] Yes
[X] No
```
=> Changed blob details

Jenkinsfile_CNP, charts/rd-judicial-data-load/Chart.yaml, charts/rd-judicial-data-load/requirements.yaml, charts/rd-judicial-data-load/values.preview.template.yaml, charts/rd-judicial-data-load/values.yaml, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-926
feat: Master Pipeline set-up for Judicial Data Load with JRD api image
No
=> feat: Master Pipeline set-up for Judicial Data Load with JRD api data base

Jenkinsfile_CNP, infrastructure/main.tf
NA
refactor: disabled DB Migration
No
=> refactor: disabled DB Migration

database/Dockerfile, src/main/resources/application.yaml
version upgrade to v11
```
[ ] Yes
[ X] No
```
=> version upgrade to v11

src/main/java/uk/gov/hmcts/reform/juddata/camel/route/ParentOrchestrationRoute.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/util/MappingConstants.java, src/main/java/uk/gov/hmcts/reform/juddata/scheduler/JrdUserProfileDataLoadScheduler.java, src/main/resources/application-jrd-router.yaml
https://tools.hmcts.net/jira/browse/RDCC-987
fix: Avoid Multiple consumer for same camel route (RDCC-987)
No
=> fix: Avoid multiple consumer for same camel route(RDCC-987)

build.gradle
https://tools.hmcts.net/jira/browse/RDCC-927
fix:sonar coverage (RDCC-927)
No
=> fix:sonar coverage

src/main/resources/application-jrd-router.yaml
NA
refactor:Blob CSV path configuration changes
No
=> refactor:Blob CSV path configuration changes

src/main/resources/application.yaml
NA
refactor: camel cron config update
No
=> refactor: camel cron config update

build.gradle
NA
refactor: azure blob version bump up
No
=> refactor: azure blob version bump up

infrastructure/main.tf
NA
refactor: app-insights configuration
No
=> refactor: app-insights configuration

infrastructure/main.tf, infrastructure/output.tf
=> refactor:updated terraform scripts to remove rg

charts/rd-judicial-data-load/Chart.yaml, charts/rd-judicial-data-load/requirements.yaml, config/owasp/suppressions.xml
=> config: updated chart version

charts/rd-judicial-data-load/Chart.yaml
NA
refactor: bump up JRD charts
No
=> refactor: bump up JRD charts

src/main/java/uk/gov/hmcts/reform/juddata/camel/processor/ArchiveAzureFileProcessor.java, src/main/resources/application-jrd-router.yaml
NA
fix: archival and time 24 hrs format postgres fix
No
=> fix: archival and time 24 hrs format postgres fix

src/main/resources/application.yaml
NA
fix:scheduler timings and email disabled
No
=> fix:scheduler timings and email disabled

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/juddata/configuration/DataSourceConfig.java, src/main/resources/application.yaml
NA
test: validate no of idle connections
No
=> test: validate no of idle connections

src/main/java/uk/gov/hmcts/reform/juddata/configuration/DataSourceConfig.java, src/main/resources/application.yaml
NA
refactor:pool size setting
No
=> refactor:pool size setting

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/juddata/configuration/DataSourceConfig.java, src/main/resources/application.yaml
NA
fix:updated datasource pool size
No
=> fix:updated datasource pool size

config/owasp/suppressions.xml, src/integrationTest/java/uk/gov/hmcts/reform/juddata/cameltest/ParentOrchestrationRouteTest.java, src/integrationTest/java/uk/gov/hmcts/reform/juddata/cameltest/ParentRouteAbstractTest.java, src/integrationTest/java/uk/gov/hmcts/reform/juddata/config/ParentCamelConfig.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/processor/JsrValidationBaseProcessor.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/route/LeafTableRoute.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/route/ParentOrchestrationRoute.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/service/AuditProcessingService.java, src/main/java/uk/gov/hmcts/reform/juddata/configuration/DataSourceConfig.java, src/main/java/uk/gov/hmcts/reform/juddata/scheduler/JrdLeafDataLoadStarter.java, src/main/java/uk/gov/hmcts/reform/juddata/scheduler/JrdUserProfileDataLoadScheduler.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/AuditProcessingServiceTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialBaseLocationProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialOfficeAppointmentProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialUserProfileProcessorTest.java
NA
fix:updated JRD auditing
No
=> fix:updated JRD auditing

src/main/resources/application.yaml
NA
refactor:scheduler timings
No
=> refactor:scheduler timings

charts/rd-judicial-data-load/Chart.yaml, config/owasp/suppressions.xml
NA
refactor: JRD helm chart bump up
No
=> refactor: JRD helm chart bump up

infrastructure/demo.tfvars, src/main/java/uk/gov/hmcts/reform/juddata/camel/task/LeafRouteTask.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/task/ParentRouteTask.java
NA
refactor: ase flag removed
No
=> refactor: ase flag removed

README.md
NA
refactor: updated readme file
No
=> refactor: updated readme file

Jenkinsfile_CNP, Jenkinsfile_parameterized, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-1399
Addressing the Vulnerabilities
```
[ ] Yes
[x] No
```
=> RDCC-1399: Addressing any Vulnerabilities

Jenkinsfile_nightly, src/main/java/uk/gov/hmcts/reform/juddata/JudicialApplication.java, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RDCC-1525
fix: App-insight log issue fix(RDCC-1525)
No
=> fix: App-insight log issue fix(RDCC-1525)

src/main/java/uk/gov/hmcts/reform/juddata/camel/processor/JsrValidationBaseProcessor.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/validator/JsrValidatorInitializer.java, src/main/resources/application-jrd-router.yaml, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialUserProfileProcessorTest.java
https://tools.hmcts.net/jira/browse/RDCC-1547
refactor: JSR exception threshold flag disabled
No
=> refactor: JSR exception threshold flag disabled

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-1740
fix: cleaned up suppressions(RDCC-1742)
No
=> fix: cleaned up suppressions(RDCC-1742)

build.gradle
NA
fix:PI Mutation plugin update
https://tools.hmcts.net/jira/browse/RDCC-1757
=> fix:PI Mutation plugin update(RDCC-1757)

build.gradle
https://tools.hmcts.net/jira/browse/RDCC-1941
build(deps):Bum up data-ingestion lib to fix health check
No
=> build(deps):Bum up data-ingestion lib to fix health check

build.gradle
RDCC-1933
This PR covers jar version bump ups and owasp update
```
[ ] Yes
[X ] No
```
=> Fix : Bump up versions and owasp update(RDCC-1933)

config/owasp/suppressions.xml
feat:nightly build fix
```
[ ] Yes
[X] No
```
=> adding suppression entry to fix the build

charts/rd-judicial-data-load/Chart.yaml, charts/rd-judicial-data-load/requirements.yaml
https://tools.hmcts.net/jira/browse/RDCC-2033
```
[ ] Yes
[X] No
```
=> Update postgres chart and bump up chart - Master

build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdBatchApplicationTest.java, src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdBatchTestValidationTest.java, src/functionalTest/java/uk/gov/hmcts/reform/juddata/config/ParentCamelConfig.java, src/functionalTest/resources/application-integration.yml, src/functionalTest/resources/application-leaf-integration.yml, src/main/java/uk/gov/hmcts/reform/juddata/camel/binder/JudicialUserProfile.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/mapper/JudicialOfficeAppointmentRowMapper.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdExecutor.java, src/main/resources/application-camel-routes-common.yaml, src/main/resources/application-jrd-leaf-router.yaml, src/main/resources/application-jrd-router-orchestartion.yaml, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialBaseLocationProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialContractTypeProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialOfficeAppointmentProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialOfficeAuthorisationProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialRegionTypeProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialUserProfileProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialUserRoleTypeProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/util/JrdExecuterTest.java
https://tools.hmcts.net/jira/browse/RDCC-2086
fix: Audit service fix for multiple spring tasklets 
No
=> fix: Audit service fix for multiple spring tasklets 

build.gradle
https://tools.hmcts.net/jira/browse/RDCC-2143
Fix the cve-2020-8908
```
[ ] Yes
[x] No
```
=> Fix the cve-2020-8908

src/main/java/uk/gov/hmcts/reform/juddata/camel/mapper/JudicialOfficeAuthorisationRowMapper.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/binder/JudicialOfficeAppointmentTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/binder/JudicialUserProfileTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/mapper/JudicialOfficeAuthorisationRowMapperTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialBaseLocationProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialOfficeAppointmentProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialOfficeAuthorisationProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialUserRoleTypeProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/task/LeafRouteTaskTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/util/JrdExecutorTest.java
https://tools.hmcts.net/jira/browse/RDCC-2187
increasing Mutation Coverage via unit tests
```
[ ] Yes
[x] No
```
=> RDCC-2187: increasing Mutation Coverage

README.md, build.gradle
NA
1. Updated org.testContainers jar
2. Remove the JrdExecutor from PiTest Suite.
```
[ ] Yes
[x] No
```
=> Fix pitest

src/functionalTest/resources/application-integration.yml, src/functionalTest/resources/db/testmigration/V1_8__alter_user_profile_table.sql, src/functionalTest/resources/sourceFiles/parent/judicial_userprofile.csv, src/functionalTest/resources/sourceFiles/parent/judicial_userprofile_jsr.csv, src/functionalTest/resources/sourceFiles/parent/judicial_userprofile_singlerecord.csv, src/main/java/uk/gov/hmcts/reform/juddata/camel/binder/JudicialUserProfile.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/mapper/JudicialUserProfileRowMapper.java, src/main/resources/application-jrd-router-orchestartion.yaml, src/main/resources/db/migration/V1_9__alter_user_profile_table.sql, src/test/java/uk/gov/hmcts/reform/juddata/camel/binder/JudicialUserProfileTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/helper/JrdTestSupport.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/mapper/JudicialUserProfileRowMapperTest.java, src/test/resources/sourceFiles/test.csv
RDCC-2410
This change will add Object ID column in JRD
```
[ ] Yes
[ X] No
```
=> feat: Add Object ID in User Profile Table(RDCC-2410)

charts/rd-judicial-data-load/Chart.yaml, charts/rd-judicial-data-load/values.preview.template.yaml, charts/rd-judicial-data-load/values.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RDCC-2505
```
[ ] Yes
[X] No
```
=> Update app insights key secret name

charts/rd-judicial-data-load/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-2645
```
[ ] Yes
[X] No
```
=> Update job chart version

src/functionalTest/resources/db/testmigration/V1_9__alter_user_profile_with_guid.sql, src/main/resources/db/migration/V1_10__alter_user_profile_with_guid.sql
https://tools.hmcts.net/jira/browse/RDCC-2643
refactor: added sidam column and updated length of object id
No
=> refactor: added sidam column and updated length of object id

build.gradle
https://tools.hmcts.net/jira/browse/RDCC-2682
refactor: Used data-ingestion library published in JIT Pack 
No
=> refactor: Used data-ingestion library published in JIT Pack 

charts/rd-judicial-data-load/Chart.yaml, charts/rd-judicial-data-load/values.preview.template.yaml, charts/rd-judicial-data-load/values.yaml, src/main/resources/bootstrap.yaml
NA
refactor: publish ASB variables
No
=> refactor: publish ASB variables

charts/rd-judicial-data-load/Chart.yaml, charts/rd-judicial-data-load/values.preview.template.yaml, charts/rd-judicial-data-load/values.yaml, src/main/resources/bootstrap.yaml
NA
refactor: updated helm variables
No
=> refactor: updated helm variables

Jenkinsfile_CNP, Jenkinsfile_nightly, charts/rd-judicial-data-load/Chart.yaml, charts/rd-judicial-data-load/values.preview.template.yaml, charts/rd-judicial-data-load/values.yaml, src/functionalTest/resources/application-integration.yml, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml
NA
refactor: Publish Launch darkly env variables
```
[ ] Yes
[X] No
```
=> refactor: Publish Launch darkly env variables

src/functionalTest/java/uk/gov/hmcts/reform/juddata/config/ParentCamelConfig.java
NA
refactor: function test case fix aat #207
```
[ ] Yes
[X] No
```
=> refactor: function test case fix aat

build.gradle
NA
fix: nightly fix
```
[ ] Yes
[X] No
```
=> fix: nightly fix

charts/rd-judicial-data-load/Chart.yaml, charts/rd-judicial-data-load/values.preview.template.yaml, charts/rd-judicial-data-load/values.yaml, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml
NA
refactor: Used boot strap
```
[ ] Yes
[X] No
```
=>  refactor: Used boot strap

charts/rd-judicial-data-load/Chart.yaml, charts/rd-judicial-data-load/values.preview.template.yaml, charts/rd-judicial-data-load/values.yaml, src/functionalTest/resources/application-integration.yml, src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdSidamTokenServiceImpl.java, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml
NA
refactor: updated sidam search query env
```
[ ] Yes
[X] No
```
=> refactor: updated sidam search query env

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/RDCC-2900
Nightly build missing security scan step and reports added
```
[ ] Yes
[X] No
```
=> RDCC-2900 Nightly build missing security scan step and reports added

Jenkinsfile_nightly, audit.json, build.gradle
JIRA link
https://tools.hmcts.net/jira/browse/RDCC-2960
- Upgraded spring boot version to fix CVE CVE-2021-22118
- Added missing properties in jenkins nightly to fix security scan reported issue
```
[ ] Yes
[x] No
```
=> fix: RDCC-2960 Fixed CVE-2021-22118 and security scan reported issue

Jenkinsfile_CNP, Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/DTSPO-3230
When this PR is merged: hmcts/cnp-jenkins-library#753 , can this also be merged?
Will announce on Slack when above PR is merged
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[X] No
=> Update DockerImage to new tagging reference

src/test/java/uk/gov/hmcts/reform/juddata/camel/util/JrdDataIngestionLibraryRunnerTest.java
NA
fix:nightly fix mutation tests
```
[ ] Yes
[X] No
```
=> fix:nightly fix mutation tests

src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdDataIngestionLibraryRunner.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/util/JrdDataIngestionLibraryRunnerTest.java
NA
fix:camel context issue of JOB id
```
[ ] Yes
[X] No
```
=> fix:camel context issue of JOB id

charts/rd-judicial-data-load/Chart.yaml, charts/rd-judicial-data-load/values.preview.template.yaml, charts/rd-judicial-data-load/values.yaml, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RDCC-2873
refactor: sendgrid configuration(RDCC-2873)
```
[ ] Yes
[X] No
```
=> refactor: sendgrid configuration(RDCC-2873)

charts/rd-judicial-data-load/Chart.yaml, src/main/resources/bootstrap.yaml
NA
fix:sendgrid configuration
```
[ ] Yes
[X] No
```
=> fix:sendgrid configuration

security.sh
=> changed the order of command in security.sh to fix security scan

src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdDataIngestionLibraryRunner.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/util/JrdDataIngestionLibraryRunnerTest.java
NA
fix: scheduler job publishing status
```
[ ] Yes
[X] No
```
=> fix: scheduler job publishing status

src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdDataIngestionLibraryRunner.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/util/JrdDataIngestionLibraryRunnerTest.java
https://tools.hmcts.net/jira/browse/RDCC-3080
fix: ASB status issue
```
[ ] Yes
[x] No
```
=> fix: ASB status issue

build.gradle, src/functionalTest/resources/application-integration.yml, src/integrationTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdBatchApplicationIntegrationTest.java, src/integrationTest/java/uk/gov/hmcts/reform/juddata/config/LeafConfig.java, src/integrationTest/java/uk/gov/hmcts/reform/juddata/config/ParentConfig.java, src/integrationTest/java/uk/gov/hmcts/reform/juddata/support/IntegrationTestSupport.java, src/integrationTest/java/uk/gov/hmcts/reform/juddata/support/JrdBatchIntegrationSupport.java, src/integrationTest/java/uk/gov/hmcts/reform/juddata/support/LeafIntegrationSupport.java, src/integrationTest/java/uk/gov/hmcts/reform/juddata/support/ParentIntegrationTestSupport.java, src/integrationTest/resources/application-integration-test.yml, src/integrationTest/resources/application-leaf-integration-test.yml, src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdDataIngestionLibraryRunner.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JsonFeignResponseUtil.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/ArchiveAzureFileProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialOfficeAppointmentProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialOfficeAuthorisationProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/util/FeatureToggleServiceImplTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/util/JrdDataIngestionLibraryRunnerTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/util/JrdSidamTokenServiceImplTest.java
https://tools.hmcts.net/jira/browse/RDCC-2992
fix: Bump up mutation with integration tests(RDCC-2992)
```
[ ] Yes
[X] No
```
=> fix: Bump up mutation with integration tests(RDCC-2992)

build.gradle
NA
fix: nightly mutation
```
[ ] Yes
[X] No
```
=> fix: nightly mutation

src/main/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialUserProfileProcessor.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/util/FeatureToggleServiceImplTest.java
NA
fix: Sonar fix
```
[ ] Yes
[X] No
```
=> fix: Sonar fix

src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdBatchAuditingAndEmailTest.java, src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/testsupport/ParentIntegrationTestSupport.java, src/main/java/uk/gov/hmcts/reform/juddata/JudicialApplication.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/util/FeatureToggleServiceImpl.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdConstants.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdDataIngestionLibraryRunner.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdSidamTokenService.java, src/main/java/uk/gov/hmcts/reform/juddata/configuration/FeignConfiguration.java, src/main/java/uk/gov/hmcts/reform/juddata/exception/JudicialDataLoadException.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/util/JrdConstantsTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/util/JsonFeignResponseUtilTest.java
https://tools.hmcts.net/jira/browse/RDCC-3158
JRD - Fix SonarQube issue in master
```
[ ] Yes
[X] No
```
=> JRD - Fix SonarQube issue in master

build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/juddata/config/ParentCamelConfig.java, src/integrationTest/java/uk/gov/hmcts/reform/juddata/config/ParentConfig.java
https://tools.hmcts.net/jira/browse/RDCC-3237
Ref Data - Fix  CVE issue : CVE-2021-28170
```
[ ] Yes
[x] No
```
=> RDCC-3237: Fix for CVE issue: CVE-2021-28170

charts/rd-judicial-data-load/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-3290
Upgraded the job chart version to latest
```
[ ] Yes
[x] No
```
=> feat: RDCC-3290 Upgraded the job chart version to latest

src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdBatchTestValidationTest.java, src/functionalTest/resources/sourceFiles/parent/judicial_userprofile_with_invalid_appointment.csv, src/main/java/uk/gov/hmcts/reform/juddata/validators/AppointmentValidator.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/validator/AppointmentValidatorTest.java
https://tools.hmcts.net/jira/browse/RDCC-3261
Additional appointment filters introduced for the user profile file. 
```
[ ] Yes
[x] No
```
=> RDCC-3261: Filter additional records from the Personal file for selected Appointments

src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdBatchTestValidationTest.java, src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/testsupport/ParentIntegrationTestSupport.java, src/functionalTest/java/uk/gov/hmcts/reform/juddata/config/ParentCamelConfig.java, src/functionalTest/resources/application-integration.yml, src/functionalTest/resources/db/testmigration/V1_24__alter_dataload_exception_records_add_row_id.sql, src/functionalTest/resources/sourceFiles/parent/judicial_office_authorisation_per_empty.csv, src/main/java/uk/gov/hmcts/reform/juddata/camel/binder/JudicialBaseLocationType.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/binder/JudicialOfficeAppointment.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/binder/JudicialOfficeAuthorisation.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/binder/JudicialRegionType.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/binder/JudicialUserProfile.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/processor/ICustomValidationProcessor.java, src/main/resources/application-camel-routes-common.yaml, src/main/resources/db/migration/V1_24__alter_dataload_exception_records_add_row_id.sql, src/test/java/uk/gov/hmcts/reform/juddata/camel/util/JrdExecutorTest.java
https://tools.hmcts.net/jira/browse/RDCC-3230
Added RowID to the exception table and populated data into it
```
[ ] Yes
[x] No
```
=> feat: RDCC-3230 Added RowID to the exception table and populated data into it

Jenkinsfile_CNP, Jenkinsfile_nightly, bin/run-in-docker.sh, charts/rd-judicial-data-load/Chart.yaml, charts/rd-judicial-data-load/values.preview.template.yaml, charts/rd-judicial-data-load/values.yaml, src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/testsupport/JrdBatchIntegrationSupport.java, src/functionalTest/java/uk/gov/hmcts/reform/juddata/config/ParentCamelConfig.java, src/functionalTest/resources/application-integration.yml, src/integrationTest/resources/application-integration-test.yml, src/main/resources/application-camel-routes-common.yaml, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/RDCC-3277
Review and remove hard code values 
```
[ ] Yes
[x] No
```
=> RDCC-3277: Created the alias names for the secrets.

build.gradle
JIRA link
https://tools.hmcts.net/jira/browse/RDCC-3557
Upgraded spring core version to fix CVE-2021-22096
```
[ ] Yes
[x] No
```
=> fix:fix: RDCC-3557 Upgraded spring core version to fix CVE-2021-22096

Jenkinsfile_CNP, Jenkinsfile_nightly, build.gradle
https://tools.hmcts.net/jira/browse/RDCC-3677
Publish Test Reports in Jenkins
```
[ ] Yes
[X] No
```
=> Publish Test Reports in Jenkins

build.gradle, src/functionalTest/resources/application-integration.yml, src/integrationTest/resources/application-integration-test.yml, src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdDataIngestionLibraryRunner.java, src/main/resources/application-camel-routes-common.yaml, src/test/java/uk/gov/hmcts/reform/juddata/camel/util/JrdDataIngestionLibraryRunnerTest.java
https://tools.hmcts.net/jira/browse/RDCC-3651
Change in logic to process previous day file
```
[ ] Yes
[X] No
```
=> Bugfix: Change in logic to process previous day file

src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/testsupport/JrdBlobSupport.java
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/RDCC-1754
Replace deprecated methods with new (Java 8 to Java 11 migration)
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[X ] No
=> RDCC-1754: Replace deprecated methods with new (Java 8 to Java 11 migration)

src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdSidamTokenServiceImpl.java
Added size query param
```
[ ] Yes
[x] No
```
=> added size parameter

charts/rd-judicial-data-load/Chart.yaml, charts/rd-judicial-data-load/values.preview.template.yaml, charts/rd-judicial-data-load/values.yaml
Removed  JRD_DATA_PER_MESSAGE
Removed  JRD_DATA_PER_MESSAGE
```
[ ] Yes
[x] No
```
=> removed jrd data per message

src/main/resources/application-jrd-router-orchestartion.yaml, src/main/resources/db/migration/V1_29__alter_judicial_role_type.sql
https://tools.hmcts.net/jira/browse/RDCC-3697
```
[ ] Yes
[ x] No
```
=> RDCC-3697:Changes made to remove duplicate records from role type

build.gradle
JIRA link
https://tools.hmcts.net/jira/browse/RDCC-3773
patch log4j to the latest version
```
[ ] Yes
[x] No
```
=>  fix: RDCC-3773 patch log4j to the latest version

build.gradle, src/functionalTest/resources/application-integration.yml, src/integrationTest/resources/application-integration-test.yml, src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdDataIngestionLibraryRunner.java, src/main/resources/application-camel-routes-common.yaml, src/test/java/uk/gov/hmcts/reform/juddata/camel/util/JrdDataIngestionLibraryRunnerTest.java
https://tools.hmcts.net/jira/browse/RDCC-3651
Duplicate sidam id publishing to ASB
```
[ ] Yes
[X] No
```
=> Bugfix: Duplicate sidam id publishing to ASB

.github/dependabot.yml
https://tools.hmcts.net/jira/browse/RDCC-3786
Added dependabot.yml file 
```
[ ] Yes
[x] No
```
=> fix: RDCC-3782 Added dependabot.yml file

.github/dependabot.yml, Jenkinsfile_nightly, README.md, build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/juddata/config/ParentCamelConfig.java, src/functionalTest/resources/application-integration.yml, src/integrationTest/resources/application-integration-test.yml, src/main/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialOfficeAuthorisationProcessor.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/util/CommonUtils.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/util/EmailTemplate.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdConstants.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdDataIngestionLibraryRunner.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdExecutor.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdUserProfileUtil.java, src/main/java/uk/gov/hmcts/reform/juddata/configuration/EmailConfiguration.java, src/main/java/uk/gov/hmcts/reform/juddata/configuration/FreemarkerConfig.java, src/main/java/uk/gov/hmcts/reform/juddata/exception/EmailException.java, src/main/resources/application-camel-routes-common.yaml, src/main/resources/application-jrd-router-orchestartion.yaml, src/main/resources/application.yaml, src/main/resources/templates/lower-level-auth.ftl, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialOfficeAuthorisationProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/util/EmailTemplateTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/util/JrdDataIngestionLibraryRunnerTest.java
https://tools.hmcts.net/jira/browse/RDCC-3802
To send email in html text format with customised template
```
[ ] Yes
[X] No
```
=> Feature: To send email in html text format with customised template

build.gradle, config/owasp/suppressions.xml
=> version upgrade and CVE fixes

src/main/java/uk/gov/hmcts/reform/juddata/camel/processor/ICustomValidationProcessor.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdDataIngestionLibraryRunner.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialBaseLocationProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialOfficeAppointmentProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialOfficeAuthorisationProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialRegionTypeProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialUserProfileProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialUserRoleTypeProcessorTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/util/EmailTemplateTest.java
https://tools.hmcts.net/jira/browse/RDCC-3462
Address remaining Sonar issues in Ref Data repos
```
[ ] Yes
[X] No
```
=> fixed sonar code issues

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-4048
Fixed CVEs
```
[ ] Yes
[x] No
```
=> RDCC-4048: Fixed CVEs

src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdDataIngestionLibraryRunner.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialUserProfileProcessorTest.java
https://tools.hmcts.net/jira/browse/RDCC-3462
Address remaining Sonar issues in Ref Data repos
```
[ ] Yes
[X] No
```
=> fixed the sonar issues

src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdBatchApplicationTest.java, src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdBatchAuditingAndEmailTest.java, src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdBatchTestValidationTest.java, src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/JrdFileStatusCheckTest.java, src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/testsupport/JrdBatchIntegrationSupport.java, src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/testsupport/ParentIntegrationTestSupport.java, src/functionalTest/resources/application-integration.yml, src/functionalTest/resources/application-leaf-integration.yml, src/integrationTest/resources/application-integration-test.yml, src/integrationTest/resources/application-leaf-integration-test.yml, src/main/resources/application-camel-routes-common.yaml, src/main/resources/application-jrd-leaf-router.yaml, src/main/resources/application-jrd-router-orchestartion.yaml
https://tools.hmcts.net/jira/browse/RDCC-3459
Refactored functional tests and SQL statements with uppercase SQL keywords
```
[ ] Yes
[X] No
```
=> Refactor: functional tests and SQL statements with uppercase SQL keywords

build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4202
fix: Ignored the fortify build failure
```
[ ] Yes
[x] No
```
=> Ignored the fortify build failure

build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4427
```
[ ] Yes
[X] No
```
=> Nightly Build failure issues

build.gradle, src/test/java/uk/gov/hmcts/reform/juddata/camel/binder/JudicialUserProfileTest.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/helper/JrdTestSupport.java
https://tools.hmcts.net/jira/browse/RDCC-4670
fix: RDCC-4670 Fixed CVE-2022-24823 by upgrading netty
```
[ ] Yes
[x] No
```
=> fix: RDCC-4670 Fixed CVE-2022-24823 by upgrading netty

src/main/resources/application-jrd-leaf-router.yaml
https://tools.hmcts.net/jira/browse/RDCC-4665
JRD : Testing using MRD test files for Judicial Reference Data
```
[ ] Yes
[X] No
```
=> fixed the region_type

build.gradle
https://tools.hmcts.net/jira/browse/RDCC-4699
CVE fix for Tomcat embed
```
[ ] Yes
[x] No
```
=> RDCC-4699: CVE fix for tomcat embed

build.gradle, charts/rd-judicial-data-load/Chart.yaml
https://tools.hmcts.net/jira/browse/RDCC-4696
Updated library version to latest
```
[ ] Yes
[x] No
```
=> Update data ingestion library version to latest - CVE Fix

build.gradle, src/test/java/uk/gov/hmcts/reform/juddata/camel/util/CommonUtilsTest.java
https://tools.hmcts.net/jira/browse/RDCC-4902
Changes made to improve code coverage
```
[ ] Yes
[x ] No
```
=> Feat:RDCC-4902:Changes made to improve code coverage

charts/rd-judicial-data-load/Chart.yaml, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-5005
Updated service bus chart version to latest
```
[ ] Yes
[x] No
```
=> RDCC-5005: Update the chart version of service bus and blob storage to the latest

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-5016
Suppressed CVE-2022-33915
```
[ ] Yes
[x] No
```
=> RDCC-5016: Fix CVE-2022-33915

charts/rd-judicial-data-load/Chart.yaml, charts/rd-judicial-data-load/values.preview.template.yaml
=> fix postgresql chart config

Jenkinsfile_CNP, src/functionalTest/resources/db/testmigration/V1_35__update_ticket_code_mapping.sql, src/main/resources/db/migration/V1_35__update_ticket_code_mapping.sql
https://tools.hmcts.net/jira/browse/RDCC-4959
Update the Ticket Code mapping table
```
[ ] Yes
[x ] No
```
=> Feat:RDCC-4959:Changes made to  update ticket_code mapping

src/functionalTest/resources/db/testmigration/V1_36__update_judicial_location_mapping.sql, src/main/resources/db/migration/V1_36__update_judicial_location_mapping.sql
https://tools.hmcts.net/jira/browse/RDCC-5000
Updated epimms id of location mapping
```
[ ] Yes
[x] No
```
=> RDCC-5000: Update the Base Location to ePIMS ID mapping table

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-4053
CVE fixes
```
[ ] Yes
[ ] No
```
=> RDCC-4053 removed the cve suppression

build.gradle, config/owasp/suppressions.xml
=> Rdcc 5392 adding suppression for CVE 2022 25857

build.gradle
CVE Issues
```
[ ] Yes
[ x] No
```
=> CVE issue-Jackson Version fix

build.gradle
https://tools.hmcts.net/jira/browse/RDCC-5675
```
[ ] Yes
[X] No
```
=> CVE Issue Fix RDCC- 5675

src/functionalTest/resources/db/testmigration/V1_40__update_judicial_service_code_mapping.sql, src/main/resources/db/migration/V1_40__update_judicial_service_code_mapping.sql
https://tools.hmcts.net/jira/browse/RDCC-5738
RDCC-5738:JRD : Update the Judicial Service Code mapping table for Family Public Law & Financial Remedy Services
```
[ ] Yes
[x ] No
```
=> Feat:RDCC-5738:JRD : Update the Judicial Service Code mapping table for Family Public Law & Financial Remedy Services

build.gradle, charts/rd-judicial-data-load/values.preview.template.yaml, charts/rd-judicial-data-load/values.yaml, src/main/java/uk/gov/hmcts/reform/elinks/configuration/ElinksFeignInterceptorConfiguration.java, src/main/java/uk/gov/hmcts/reform/elinks/configuration/FeignConfiguration.java, src/main/java/uk/gov/hmcts/reform/elinks/configuration/FeignHeaderConfig.java, src/main/java/uk/gov/hmcts/reform/elinks/feign/ElinksFeignClient.java, src/main/java/uk/gov/hmcts/reform/elinks/util/RefDataConstants.java, src/main/resources/application.yaml
JIRA link (if applicable) 
https://tools.hmcts.net/jira/browse/RDCC-5940
Change description 
ElinksFeignClient , api key changes
Does this PR introduce a breaking change?
```
[ ] Yes
[ X] No
```
=> ElinksFeignClient , api key changes

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized
https://tools.hmcts.net/jira/browse/RDCC-5931
```
[ ] Yes
[X] No
```
=> Replace after with afterSuccess for depreciated : RDCC-5931

src/functionalTest/resources/db/testmigration/V1_48__elinks_alter_tables.sql, src/main/resources/db/migration/V1_48__elinks_alter_tables.sql
https://tools.hmcts.net/jira/browse/RDCC-6027
eLinks : Update the tables for Judicial Reference Data
```
[ ] Yes
[ x] No
```
=> Feat:RDCC-6027:eLinks : Update the tables for Judicial Reference Data

src/functionalTest/resources/db/testmigration/V1_50__elinks_alter_tables.sql, src/main/resources/db/migration/V1_50__elinks_alter_tables.sql
https://tools.hmcts.net/jira/browse/RDCC-6048
Make Id columns in appointments , authorisation tables as auto inrement
```
[ ] Yes
[x ] No
```
=> Feat:RDCC-6048:Altered tables for elinks people api

src/functionalTest/resources/application-integration.yml, src/integrationTest/resources/application-integration-test.yml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RDCC-6182
```
[ ] Yes
[ ] No
```
=> Email change

build.gradle, charts/rd-judicial-data-load/Chart.yaml, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-6244
[RDCC-6244] OWASP update for Judicial Data laod repo
```
[ ] Yes
[ x] No
```
=> [RDCC-6244] OWASP update for Judicial Data laod repo

build.gradle
https://tools.hmcts.net/jira/browse/RDCC-6259
[RDCC-6259]- JRD load PITESt fix
```
[ ] Yes
[x ] No
```
=> [RDCC-6259]- JRD load PITESt fix

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDCC-6234
[RDCC-6234] Address CVEs in all Reference Data repositories - Judicial Reference Data
```
[ ] Yes
[x ] No
```
=> [RDCC-6234] Address CVEs in all Reference Data repositories - Judicial Reference Data

src/main/java/uk/gov/hmcts/reform/juddata/camel/processor/JudicialOfficeAuthorisationProcessor.java, src/main/java/uk/gov/hmcts/reform/juddata/camel/util/JrdExecutor.java, src/test/java/uk/gov/hmcts/reform/juddata/camel/util/CommonUtilsTest.java
Address Sonar Major and Minor Issues
```
[ ] Yes
[X] No
```
=> Sonar address coverage

Jenkinsfile_CNP, build.gradle, charts/rd-judicial-data-load/Chart.yaml, charts/rd-judicial-data-load/values.preview.template.yaml, src/functionalTest/resources/application-integration.yml
https://tools.hmcts.net/jira/browse/DTSRD-148
new helm chart 1.0.0 and resulting pipeline and build config changes
```
[ ] Yes
[x] No
```
=> updating helm chart

src/functionalTest/resources/db/testmigration/V1_56__elinks_shed_scheduler_table.sql, src/main/resources/db/migration/V1_56__elinks_shed_scheduler_table.sql
[RDCC-6704]Added Flyway script as part of user story to sync all repo
https://tools.hmcts.net/jira/browse/RDCC-6704
```
[ ] Yes
[x ] No
```
=> [RDCC-6704]Added Flyway script as part of user story to sync all repo

src/functionalTest/resources/db/testmigration/V1_57__elinks_alter.sql, src/main/resources/db/migration/V1_57__elinks_alter.sql
https://tools.hmcts.net/jira/browse/RDCC-6627
```
[ ] Yes
[ ] No
```
=> eLinks : Data model changes to support eLinks V5.0 API specifications

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSRD-315
addresses CVE-2023-20873
remedied in spring-boot 2.7.11 - https://spring.io/security/cve-2023-20873
addresses CVE-2023-20862
remedied in spring-security 5.7.8 - https://spring.io/security/cve-2023-20862
```
[ ] Yes
[x] No
```
=> addresses CVE-2023-20873, CVE-2023-20862

charts/rd-judicial-data-load/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSRD-457
Upgrade chart-job to v 1.0.0
```
[ ] Yes
[x] No
```
=> Upgrade chart-job to v 1.0.0

src/functionalTest/java/uk/gov/hmcts/reform/juddata/cameltest/testsupport/ParentIntegrationTestSupport.java
https://tools.hmcts.net/jira/browse/RDCC-6746
[RDCC-6746]upgrade deprecated methods to java 17
```
[ ] Yes
[x ] No
```
=> [RDCC-6746]upgrade deprecated methods to java 17

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSRD-47
Removed suppressions for remedied CVEs
```
[ ] Yes
[x] No
```
=> removed suppressions

build.gradle
https://tools.hmcts.net/jira/browse/DTSRD-550
fix CVE-2023-20883
```
[ ] Yes
[x] No
```
=> DTSRD-555: fix CVE-2023-20883

.github/renovate.json, renovate.json
https://tools.hmcts.net/jira/browse/DTSRD-362
Renovate configuration
```
[ ] Yes
[x] No
```
=> Renovate config

build.gradle, src/main/resources/db/migration/V1_63__elinks_insert_cft_region_type_table.sql
https://tools.hmcts.net/jira/browse/RDCC-6024
```
[ ] Yes
[X] No
```
=> eLinks : Populate the data in cft_region_type table using flyway script.

src/main/resources/application-camel-routes-common.yaml
=> updating sidam qeury for the the first run. 

src/main/resources/application-camel-routes-common.yaml
https://tools.hmcts.net/jira/browse/RDCC-6882
[RDCC-6882](https://tools.hmcts.net/jira/browse/RDCC-6882)
```
[ ] Yes
[ X] No
```
=> Update IDAM query

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/DTSRD-792
Suppress CVE-2023-34442 while I work on the actual fix
```
[ ] Yes
[x] No
```
=> Suppress CVE-2023-34442 - working on fix

build.gradle
=> CVE fix CVE-2023-34034

src/functionalTest/resources/db/testmigration/V1_73__elinks_alter_dataload_exception.sql, src/functionalTest/resources/db/testmigration/V1_74__elinks_insert_user_profile.sql, src/functionalTest/resources/db/testmigration/V1_75__elinks_insert_jrd_lrd_region_mapping.sql, src/functionalTest/resources/db/testmigration/V1_76__elinks_alter_appointment_foreign_key_nonNull.sql, src/functionalTest/resources/db/testmigration/V1_77__judicial_ticket_code_mapping.sql, src/functionalTest/resources/db/testmigration/V1_78__judicial_service_code_mapping.sql, src/functionalTest/resources/db/testmigration/V1_79__elinks_insert_jrd_lrd_region_mapping.sql, src/main/resources/db/migration/V1_73__judicial_service_code_mapping.sql, src/main/resources/db/migration/V1_74__judicial_ticket_code_mapping.sql, src/main/resources/db/migration/V1_75__elinks_insert_jrd_lrd_region_mapping.sql, src/main/resources/db/migration/V1_76__elinks_alter_appointment_foreign_key_nonNull.sql, src/main/resources/db/migration/V1_77__elinks_insert_jrd_lrd_region_mapping.sql
https://tools.hmcts.net/jira/browse/RDCC-7001
```
[ ] Yes
[X] No
```
=> flyway changes

.github/renovate.json, build.gradle
- Updating renovate config.
https://tools.hmcts.net/jira/browse/DTSRD-1221
```
[ ] Yes
[x] No
```
=> DTSRD-1221

Jenkinsfile_nightly
=> Change schedule to run at 9:10AM

src/functionalTest/resources/db/testmigration/V1_89__elinks_insert_jrd_lrd_region_mapping.sql, src/main/resources/db/migration/V1_87__elinks_insert_jrd_lrd_region_mapping.sql
https://tools.hmcts.net/jira/browse/RDCC-7167
=> eLinks : Region Mapping Update

config/owasp/suppressions.xml
=> Update suppressions.xml for CVE-2023-4759

build.gradle, charts/rd-judicial-data-load/Chart.yaml, config/owasp/suppressions.xml
Suppresses CVE-2023-36052 (likely a false positive)
Remedies CVE-2023-35887
=> Addresses CVE-2023-36052, CVE-2023-35887

src/functionalTest/resources/db/testmigration/V1_90__elinks_insert_location_mapping_jrd_lrd.sql, src/main/resources/db/migration/V1_88__elinks_insert_location_mapping_jrd_lrd.sql
INSERT mappings data
- [ X] Does this PR introduce a breaking change
=> changing fly way version to 88 and functional fly way

src/functionalTest/resources/db/testmigration/V1_91__elinks_insert_service_code_mapping.sql, src/main/resources/db/migration/V1_89__elinks_insert_service_code_mapping.sql
https://tools.hmcts.net/jira/browse/RDCC-7230
Update Service Code Mapping table
- [ x] Does this PR introduce a breaking change
=> Update Service Code Mapping table

src/functionalTest/resources/db/testmigration/V1_92__elinks_alter_judicIal_userProfile.sql, src/main/resources/db/migration/V1_90__elinks_alter_judicial_user_profile.sql
https://tools.hmcts.net/jira/browse/RDCC-7237
=> alter judicial_user_profile

src/functionalTest/resources/db/testmigration/V1_93__elinks_alter_judicIal_userProfile.sql, src/main/resources/db/migration/V1_91__elinks_jrd_lrd_region_mapping.sql
https://tools.hmcts.net/jira/browse/RDCC-7158
=> eLinks : Region Mapping Update for eLinks Go-Live

src/functionalTest/resources/db/testmigration/V1_94__elinks_jrd_lrd_region_mapping.sql, src/main/resources/db/migration/V1_92__elinks_jrd_lrd_region_mapping.sql
https://tools.hmcts.net/jira/browse/RDCC-7267
=> elinks : location mapping table update

config/owasp/suppressions.xml
=> Suppress CVE-2023-48795

charts/rd-judicial-data-load/Chart.yaml
=> updating charts version

build.gradle, charts/rd-judicial-data-load/Chart.yaml
=> Addresses CVE-2023-34042

build.gradle
=> Pitest logging

build.gradle
=> Pitest functional tests

build.gradle
=> Update build.gradle, disable verbose Pitest logging

charts/rd-judicial-data-load/Chart.yaml, charts/rd-judicial-data-load/values.yaml
=> Postgres V11 Decomission

build.gradle
DTSRD-3710 Reverts hmcts/rd-judicial-data-load#752
=> DTSRD-3710 Revert "Update dependency org.pitest:pitest to v1.17.1"

infrastructure/terraform.tf
https://tools.hmcts.net/jira/browse/CME-296
- [x ] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
- [x ] tests have been updated / new tests has been added (if needed)
- [x ] Does this PR introduce a breaking change
=> CME-296: Update azurerm

build.gradle
Update snakeyaml due to CVE-2022-1471
=> Update snakeyaml to 2.3

config/owasp/suppressions.xml
Update suppressions to include CVE-2024-43591
=> Nightly build fix

charts/rd-judicial-data-load/Chart.yaml
https://tools.hmcts.net/jira/browse/CME-406
- [ x] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
- [ x] Does this PR introduce a breaking change
=> CME-406: Update OCI endpoint 
